name: Update Projects Overview

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Projects Overview
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "PROJECTS:START"
          subhead: "🚀 My Projects"
          footer: "PROJECTS:END"
          readmePath: "README.md"
          repoCount: "6"
          repoPerRow: "3"
          imageSize: "150"
          excludeEvent: '["ForkEvent","WatchEvent"]'
          excludeRepo: "[]"
