name: Update Projects Overview

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "🚀 Projects Overview"
          subhead: "A live snapshot of my most active repositories."
          footer: ""
          path: "README.md"
          repoCount: "6"
          reposPerRow: "3"
          imageSize: "150"
          excludeActivity: '["ForkEvent","WatchEvent"]'
          excludeRepo: "[]"
